// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NaeRaces.Query.EntityFrameworkCore;

#nullable disable

namespace NaeRaces.Query.EntityFrameworkCore.SqlServer.Migrations
{
    [DbContext(typeof(NaeRacesQueryDbContext))]
    [Migration("20260410112236_AddIsPublishedToRaceInformation")]
    partial class AddIsPublishedToRaceInformation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.ClubDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FounderPilotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClubDetails");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.ClubLocation", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHomeLocation")
                        .HasColumnType("bit");

                    b.Property<string>("LocationInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimezoneOffsetMinutes")
                        .HasColumnType("int");

                    b.Property<bool?>("UseDaylightSavings")
                        .HasColumnType("bit");

                    b.HasKey("ClubId", "LocationId");

                    b.ToTable("ClubLocations");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.ClubMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRegistrationConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("MembershipLevelId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentOptionId")
                        .HasColumnType("int");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RegistrationValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RegistrationValidatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ClubMembers");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.ClubMemberRole", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClubId", "PilotId", "Role");

                    b.ToTable("ClubMemberRoles");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.ClubMembershipLevel", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MembershipLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PilotPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("PolicyVersion")
                        .HasColumnType("bigint");

                    b.HasKey("ClubId", "MembershipLevelId");

                    b.ToTable("ClubMembershipLevels");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.ClubMembershipLevelPaymentOption", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MembershipLevelId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentOptionId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DayOfMonthDue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentInterval")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ClubId", "MembershipLevelId", "PaymentOptionId");

                    b.ToTable("ClubMembershipLevelPaymentOption");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.ClubOverview", b =>
                {
                    b.Property<Guid>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeLocationAddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeLocationAddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeLocationCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeLocationCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeLocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeLocationPostcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalMemberCount")
                        .HasColumnType("int");

                    b.HasKey("ClubId");

                    b.ToTable("ClubOverviews");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.ClubUniquenessDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClubUniquenessDetails");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.PilotAgeValidation", b =>
                {
                    b.Property<Guid>("PilotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ValidatedByPilotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ValidatedByClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOnClubCommittee")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PilotId", "ValidatedByPilotId", "ValidatedByClubId");

                    b.ToTable("PilotAgeValidations");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.PilotClubDetails", b =>
                {
                    b.Property<Guid>("PilotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClubCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClubName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeLocationAddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeLocationAddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeLocationCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeLocationCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeLocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeLocationPostcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MembershipLevelId")
                        .HasColumnType("int");

                    b.Property<string>("MembershipLevelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MembershipValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("PilotId", "ClubId");

                    b.ToTable("PilotClubDetails");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.PilotDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Callsign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PilotDetails");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.PilotFollowedClub", b =>
                {
                    b.Property<Guid>("PilotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PilotId", "ClubId");

                    b.ToTable("PilotFollowedClubs");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.PilotGovernmentDocumentValidation", b =>
                {
                    b.Property<Guid>("PilotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GovernmentDocument")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ValidatedByPilotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ValidatedByClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOnClubCommittee")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PilotId", "GovernmentDocument", "ValidatedByPilotId", "ValidatedByClubId");

                    b.ToTable("PilotGovernmentDocumentValidations");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.PilotInsuranceProviderValidation", b =>
                {
                    b.Property<Guid>("PilotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InsuranceProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ValidatedByPilotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ValidatedByClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOnClubCommittee")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PilotId", "InsuranceProvider", "ValidatedByPilotId", "ValidatedByClubId");

                    b.ToTable("PilotInsuranceProviderValidations");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.PilotPolicyStatement", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatementId")
                        .HasColumnType("int");

                    b.Property<string>("GovernmentDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsWithinBrackets")
                        .HasColumnType("bit");

                    b.Property<int?>("LeftHandStatementId")
                        .HasColumnType("int");

                    b.Property<int?>("MaximumAge")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<string>("Operand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequiredClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RequiredMembershipLevelId")
                        .HasColumnType("int");

                    b.Property<int?>("RightHandStatementId")
                        .HasColumnType("int");

                    b.Property<string>("StatementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolicyId", "StatementId");

                    b.ToTable("PilotPolicyStatements");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.PilotRaceRegistration", b =>
                {
                    b.Property<Guid>("PilotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PilotId", "RaceId");

                    b.ToTable("PilotRaceRegistrations");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.PilotSelectionPolicyDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LatestVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RootStatementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PilotSelectionPolicyDetails");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.RaceDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FirstRaceDateStart")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDetailsPublished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTeamRace")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastRaceDateEnd")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfRaceDates")
                        .HasColumnType("int");

                    b.Property<Guid?>("PilotPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("PilotPolicyVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RaceDetails");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.RaceInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClubName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstRaceDateStart")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastRaceDateEnd")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaximumPilots")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfRaceDates")
                        .HasColumnType("int");

                    b.Property<int>("RegisteredPilotCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RaceInformation");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.RacePackage", b =>
                {
                    b.Property<Guid>("RaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RacePackageId")
                        .HasColumnType("int");

                    b.Property<bool>("ApplyDiscounts")
                        .HasColumnType("bit");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRegistrationManuallyOpened")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PilotPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("PolicyVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegistrationCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegistrationOpenDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RaceId", "RacePackageId");

                    b.ToTable("RacePackages");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.ReactionPosition", b =>
                {
                    b.Property<string>("ReactionKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("GlobalPosition")
                        .HasColumnType("bigint");

                    b.HasKey("ReactionKey");

                    b.ToTable("ReactionPositions");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeamId", "PilotId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.ClubMembershipLevelPaymentOption", b =>
                {
                    b.HasOne("NaeRaces.Query.EntityFrameworkCore.Models.ClubMembershipLevel", "MembershipLevel")
                        .WithMany("PaymentOptions")
                        .HasForeignKey("ClubId", "MembershipLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipLevel");
                });

            modelBuilder.Entity("NaeRaces.Query.EntityFrameworkCore.Models.ClubMembershipLevel", b =>
                {
                    b.Navigation("PaymentOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
